# File: .github/workflows/scaffold.yml
# Versione finale con i permessi corretti

name: Create Project Structure

on:
  workflow_dispatch:

jobs:
  scaffold-project:
    runs-on: ubuntu-latest
    
    # --- MODIFICA RICHIESTA QUI ---
    # Aggiungiamo questo blocco per dare all'azione i permessi
    # necessari per fare il "commit" e "push" sul repository.
    permissions:
      contents: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Create Project Files
        run: |
          touch streamlit_app.py
          touch data_handler.py
          touch indicator_calculator.py
          touch backtester.py
          touch performance_analyzer.py
          touch requirements.txt
          echo "Project structure created by GitHub Action" > README.md
          
      - name: Commit and Push new files
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'actions-bot@github.com'
          git add .
          git commit -m "feat: Add project file structure via Action"
          git push
